config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/result", to: "spots#result"

  resources :spots, only: :index do
    collection do
      get :share
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :User
end

app/models/spot.rb
class Spot < ApplicationRecord
  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  has_many :Bookmark
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  #meta tag setup
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  def index
    first_address
    second_address
    center_point
    @client = GooglePlaces::Client.new(ENV['GOOGLE_API_KEY'])
    marked_results
    marker(@spots)
    location_markers

    # single_marker(@first_address_coordinates)

  end

  def share
    @first_address = params[:first_address]
    @second_address = params[:second_address]
  end

  def result
    # we cannot use show, we had to call it differently
    @client = GooglePlaces::Client.new(ENV['GOOGLE_API_KEY'])
    @result = @client.spot(params[:place_id])
    @url = @result.photos[0].fetch_url(800)
    single_marker(@result)
  end

  private

  def first_address
    @first_address = params[:first_address]
    @first_address = Geocoder.search(params[:first_address])
    @first_address_coordinates = @first_address.first.coordinates
  end

  def second_address
    @second_address = params[:second_address]
    @second_address = Geocoder.search(params[:second_address])
    @second_address_coordinates = @second_address.first.coordinates
  end

  def center_point
    @centre_point = Geocoder::Calculations.geographic_center([@first_address_coordinates, @second_address_coordinates])
    @centre_point_lat = @centre_point.first
    @centre_point_lon = @centre_point.second
  end

  def marked_results
    @spots = @client.spots(@centre_point_lat, @centre_point_lon, :types => params[:spot_type].downcase, :radius => 1000)
    @spots = @spots.take(3)
  end

  def marker(spots)
    @markers = spots.map do |spot|
      {
        lat: spot.lat,
        lng: spot.lng,
        image_url: helpers.asset_url("#{params[:spot_type]}.png")
      }

    end
  end

  def single_marker(result)
    @marker = [
      {
        lat: result.lat,
        lng: result.lng,
        image_url: helpers.asset_url("#{params[:spot_type]}.png")
      }
    ]
  end

  def location_markers
    @markers << {
                  lat: @first_address_coordinates[0],
                  lng: @first_address_coordinates[1],
                  image_url: helpers.asset_url("location.png")
                }
    @markers << {
                  lat: @second_address_coordinates[0],
                  lng: @second_address_coordinates[1],
                  image_url: helpers.asset_url("location.png")
                }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= favicon_link_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <%# meta tag c&p %>
      <!-- Facebook Open Graph data -->
      <meta property="og:title" content="<%= meta_title %>" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="<%= request.original_url %>" />
      <meta property="og:image" content="<%= meta_image %>" />
      <meta property="og:description" content="<%= meta_description %>" />
      <meta property="og:site_name" content="<%= meta_title %>" />

      <!-- Twitter Card data -->
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:title" content="<%= meta_title %>">
      <meta name="twitter:description" content="<%= meta_description %>">
      <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:image:src" content="<%= meta_image %>">
    <%# meta tag c&p /%>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>

    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage-container">

  <div class="logo-info-wrapper">
    <%= image_tag 'logo.png' %>
    <h1 class="meeter-tagline">MEET UP WITH YOUR FRIENDS WITHOUT GOING A METER TOO FAR</h1>
  </div>
  <div class="form-wrapper px-4">
    <%= form_with url: "/spots", method: :get, local: :true do |form| %>
      <div class="search-field-container">
        <%= form.text_field :first_address, placeholder: "your location", class: "address", value: params[:first_address] || "" %>
         <div class="location-btn"></div>
      </div>
      <%= form.text_field :second_address, placeholder: "your friend's location", class: "address", value: params[:second_address] || ""%>
      <div class="category-wrapper d-flex flex-wrap justify-content-between">
          <%= form.radio_button :spot_type, "park", class: "category-selector" %>
            <%= form.label :spot_type_park do %>
              <div class="category-item park">
                <%= image_tag 'park.png', width: "40" %>
                Park
              </div>
            <% end %>
          <%= form.radio_button :spot_type, "bar", class: "category-selector" %>
          <%= form.label :spot_type_bar do %>
            <div class="category-item bar">
              <%= image_tag 'bar.png', width: "40" %>
              Bar
            </div>
          <% end %>

          <%= form.radio_button :spot_type, "cafe", class: "category-selector" %>
          <%= form.label :spot_type_cafe do %>
            <div class="category-item cafe mt-2">
              <%= image_tag 'cafe.png', width: "40" %>
              Cafe
            </div>
          <% end %>
          <%= form.radio_button :spot_type, "restaurant", class: "category-selector" %>
          <%= form.label :spot_type_restaurant do %>
            <div class="category-item restaurant mt-2">
              <%= image_tag 'restaurant.png', width: "40" %>
              Restaurant
            </div>
          <% end %>
      </div>
      <%= form.submit "LET'S GO!", class: "my-button home-button" %>
    <% end %>
  </div>



</div>

app/views/pages/spots.html.erb
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

</div>


<button>Share Your Selection</button>



<script src='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js'></script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/spots/index.html.erb
<div id="map" class="index-map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">


<div class="index-content">
  <div class="scrolling-wrapper">
    <% @spots.each do |spot| %>
    <%= link_to result_path(place_id: spot.place_id, url: request.url, spot_type: params[:spot_type], first_address: params[:first_address] || nil, second_address: params[:second_address] || nil) do%>

      <div class="card-category horizontal-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= spot.photos.any? ? spot.photos[0].fetch_url(500) : "https://picsum.photos/id/1060/600/900" %>)">


        <div class="card-info">
          <h1><%= spot.name %>

             <%# <%= link_to spot.name, result_path(place_id: spot.place_id, url: request.url, spot_type: params[:spot_type]) %>
<!--             <%= link_to spot.name, result_path(place_id: spot.place_id, url: request.url) %> -->
          </h1>

          <% spot.rating.to_i.times do %>
            <span>⭐️</span>
          <% end %>

          <% if spot.opening_hours.nil? %>
            <h6>CHECK WEBSITE FOR OPENING HOURS</h6>
            <% elsif spot.opening_hours["open_now"] %>
            <h6>OPEN NOW</h6>
          <%else%>
            <h6>CURRENTLY CLOSED</h6>
          <%end%>
        </div>

      </div>
      <% end %>
    <% end %>
  </div>

  <%=link_to "share", share_spots_path(url:request.url, first_address: params[:first_address] || nil, second_address: params[:second_address] || nil), :class => "my-button button-fullwidth" %>
</div>


</div>

app/views/spots/result.html.erb
<!-- app/views/result/show.html.erb -->
<% content_for :meta_title, @result.name %>
<% content_for :meta_description, @result.website %>
<% content_for :meta_image, image_path("bar.png") %>



<div>
  <img class='img-show' src="<%= @url %>" alt="spot photo">
</div>
<div class="main-container">


  <div class="result-info">
    <h1><strong><%= @result.name %></strong></h1>
    <% @result.rating.to_i.times do %>
      <span>⭐️</span>
    <% end %>
    <h2> <i class="fa-li fa fa-map-marker-alt"></i> <%= @result.formatted_address %> </h2>
    <ul class="fa-ul">
      <li><i class="fa-li fa fa-phone-alt"></i> <a href="tel:<%= @result.international_phone_number %>" class="go-to-website"> <%= @result.international_phone_number.present? ? @result.international_phone_number : "--" %> </a> </li>
      <li><i class="fa-li fa fa-globe-europe"></i> <a href="<%= @result.website %>" class="go-to-website"> <%= @result.website.present? ? @result.website : "--" %> </a> </li>
      <li>
        <i class="fa-li fa fa-euro-sign"> </i>
        <% if @result.price_level.present? %>
        <% @result.price_level.times do %>
            <span style="font-size: 1.2rem;">💵</span>
          <% end %>
        <% else %>
          <%= "--" %>
        <% end %>
      </li>
      <li><i class="fa-li fa fa-clock"> </i>
        <% if @result.opening_hours["open_now"] %>
          Open now
        <%else%>
          Currently closed
        <%end%>
      </li>

      <li><i class="fa-li fa fa-calendar"> </i>
        <%= link_to "Business Hours ↓", "#collapseExample", data: { toggle: "collapse"}, role: "button", aria: {expanded: false, controls: "collapseExample"} %>
        <div class="collapse" id="collapseExample">
        <% @result.opening_hours["weekday_text"].each do |day| %>
          <p class="mb-0"><%= day %></p>
        <% end %>
      </div>
      </li>
    </ul>
  </div>


  <div id="map" class="result-map"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="page-buttons d-flex align-items-end">
    <a href="<%=params[:url] %>" class="my-button button-50-width" id="back-button" >Back</a>
    <%=link_to "Share", share_spots_path(url:request.url, first_address: params[:first_address] || nil, second_address: params[:second_address] || nil), :class => "my-button button-50-width"%>
  </div>

</div>

app/views/spots/share.html.erb
<div class="center-share">
  <div id="logo-share">
    <%= link_to root_path(first_address: @first_address, second_address: @second_address) do %>
      <%= image_tag("logo.png") %>
    <% end %>
  </div>

  <div class="card">
    <h5 class="card-title">Share your options</h5>
    <div class="card-body">
      <a href="whatsapp://send?text=<%= params[:url] %>"><i class="fab fa-whatsapp"></i></a>
      <a href=https://t.me/share/url?url=<%= params[:url] %>&text=Check this places"><i class="fab fa-telegram"></i></a>
      <a href="mailto:?subject=Check all this spots&amp;body=Check out these spots <%= params[:url] %>"><i class="fas fa-envelope"></i></a>
      </div>
      <div class="card-copy">
        <p id="share-link"><%= params[:url]%></p>
        <p><i class="far fa-copy"></i></p>

    </div>
  </div>
  <a href="<%=params[:url] %>" class="my-button button-fullwidth share-button">Back</a>
</div>


<input type="text" value="<%= params[:url]%>" id="myInput">
<%# <p onclick="myFunction()"><i class="far fa-copy"></i></p> %>